# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neigbor',
        ),
        migrations.AddField(
            model_name='profile',
            name='neigbor',
            field=models.ManyToManyField(to='neighbours.Neighbour'),
        ),
    ]
