# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0002_auto_20190529_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secondaryEmail',
            field=models.CharField(default='@gmail.com', max_length=50),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neigbor',
        ),
        migrations.AddField(
            model_name='profile',
            name='neigbor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='neighbours.Neighbour'),
            preserve_default=False,
        ),
    ]
