# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-30 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0005_feeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='image',
            field=models.ImageField(blank=True, upload_to='feeds/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
