# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-01 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0006_auto_20190530_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbour',
            name='hospital',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='neighbour',
            name='police',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secondaryEmail',
            field=models.EmailField(max_length=50),
        ),
    ]
